// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: classic_restorepb.proto

package classic_restorepb

import (
	"fmt"
	"io"
	"math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	brpb "github.com/pingcap/kvproto/pkg/brpb"
	import_sstpb "github.com/pingcap/kvproto/pkg/import_sstpb"
	kvrpcpb "github.com/pingcap/kvproto/pkg/kvrpcpb"
	metapb "github.com/pingcap/kvproto/pkg/metapb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PrepareTaskErrorCode describes the caller action, not the Worker's internal
// dependency error tree.
type PrepareTaskErrorCode int32

const (
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_UNSPECIFIED             PrepareTaskErrorCode = 0
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_INVALID_ARGUMENT        PrepareTaskErrorCode = 1
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_UNSUPPORTED             PrepareTaskErrorCode = 2
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_BUSY                    PrepareTaskErrorCode = 3
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_EXECUTION_FAILED        PrepareTaskErrorCode = 4
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_CANCELLED               PrepareTaskErrorCode = 5
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_CONFLICT                PrepareTaskErrorCode = 6
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_CORRUPTION              PrepareTaskErrorCode = 7
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_INTERNAL                PrepareTaskErrorCode = 8
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_TARGET_MISMATCH         PrepareTaskErrorCode = 9
	PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_SOURCE_BACKEND_MISMATCH PrepareTaskErrorCode = 10
)

var PrepareTaskErrorCode_name = map[int32]string{
	0:  "PREPARE_TASK_ERROR_CODE_UNSPECIFIED",
	1:  "PREPARE_TASK_ERROR_CODE_INVALID_ARGUMENT",
	2:  "PREPARE_TASK_ERROR_CODE_UNSUPPORTED",
	3:  "PREPARE_TASK_ERROR_CODE_BUSY",
	4:  "PREPARE_TASK_ERROR_CODE_EXECUTION_FAILED",
	5:  "PREPARE_TASK_ERROR_CODE_CANCELLED",
	6:  "PREPARE_TASK_ERROR_CODE_CONFLICT",
	7:  "PREPARE_TASK_ERROR_CODE_CORRUPTION",
	8:  "PREPARE_TASK_ERROR_CODE_INTERNAL",
	9:  "PREPARE_TASK_ERROR_CODE_TARGET_MISMATCH",
	10: "PREPARE_TASK_ERROR_CODE_SOURCE_BACKEND_MISMATCH",
}

var PrepareTaskErrorCode_value = map[string]int32{
	"PREPARE_TASK_ERROR_CODE_UNSPECIFIED":             0,
	"PREPARE_TASK_ERROR_CODE_INVALID_ARGUMENT":        1,
	"PREPARE_TASK_ERROR_CODE_UNSUPPORTED":             2,
	"PREPARE_TASK_ERROR_CODE_BUSY":                    3,
	"PREPARE_TASK_ERROR_CODE_EXECUTION_FAILED":        4,
	"PREPARE_TASK_ERROR_CODE_CANCELLED":               5,
	"PREPARE_TASK_ERROR_CODE_CONFLICT":                6,
	"PREPARE_TASK_ERROR_CODE_CORRUPTION":              7,
	"PREPARE_TASK_ERROR_CODE_INTERNAL":                8,
	"PREPARE_TASK_ERROR_CODE_TARGET_MISMATCH":         9,
	"PREPARE_TASK_ERROR_CODE_SOURCE_BACKEND_MISMATCH": 10,
}

func (x PrepareTaskErrorCode) String() string {
	return proto.EnumName(PrepareTaskErrorCode_name, int32(x))
}

func (PrepareTaskErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6d5c0dabd4bdbfec, []int{0}
}

// PrepareTaskRequestV1 starts one physical execution of an immutable Region
// restore task. task_spec is hashed exactly as received and is therefore kept
// as opaque bytes at this transport boundary.
type PrepareTaskRequestV1 struct {
	PrepareExecutionId uint64 `protobuf:"varint,1,opt,name=prepare_execution_id,json=prepareExecutionId,proto3" json:"prepare_execution_id,omitempty"`
	// Serialized ClassicRestoreTaskSpecV1 bytes. Producers must persist and
	// reuse these exact bytes for retries of the same task.
	TaskSpec      []byte           `protobuf:"bytes,2,opt,name=task_spec,json=taskSpec,proto3" json:"task_spec,omitempty"`
	RuntimeAccess *RuntimeAccessV1 `protobuf:"bytes,3,opt,name=runtime_access,json=runtimeAccess,proto3" json:"runtime_access,omitempty"`
}

func (m *PrepareTaskRequestV1) Reset()         { *m = PrepareTaskRequestV1{} }
func (m *PrepareTaskRequestV1) String() string { return proto.CompactTextString(m) }
func (*PrepareTaskRequestV1) ProtoMessage()    {}
func (*PrepareTaskRequestV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5c0dabd4bdbfec, []int{0}
}
func (m *PrepareTaskRequestV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PrepareTaskRequestV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PrepareTaskRequestV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PrepareTaskRequestV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareTaskRequestV1.Merge(m, src)
}
func (m *PrepareTaskRequestV1) XXX_Size() int {
	return m.Size()
}
func (m *PrepareTaskRequestV1) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareTaskRequestV1.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareTaskRequestV1 proto.InternalMessageInfo

func (m *PrepareTaskRequestV1) GetPrepareExecutionId() uint64 {
	if m != nil {
		return m.PrepareExecutionId
	}
	return 0
}

func (m *PrepareTaskRequestV1) GetTaskSpec() []byte {
	if m != nil {
		return m.TaskSpec
	}
	return nil
}

func (m *PrepareTaskRequestV1) GetRuntimeAccess() *RuntimeAccessV1 {
	if m != nil {
		return m.RuntimeAccess
	}
	return nil
}

// RuntimeAccessV1 carries source access material that may rotate between
// retries and therefore must not become part of the immutable TaskSpec.
type RuntimeAccessV1 struct {
	StorageBackend *brpb.StorageBackend `protobuf:"bytes,1,opt,name=storage_backend,json=storageBackend,proto3" json:"storage_backend,omitempty"`
	CipherInfo     *brpb.CipherInfo     `protobuf:"bytes,2,opt,name=cipher_info,json=cipherInfo,proto3" json:"cipher_info,omitempty"`
}

func (m *RuntimeAccessV1) Reset()         { *m = RuntimeAccessV1{} }
func (m *RuntimeAccessV1) String() string { return proto.CompactTextString(m) }
func (*RuntimeAccessV1) ProtoMessage()    {}
func (*RuntimeAccessV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5c0dabd4bdbfec, []int{1}
}
func (m *RuntimeAccessV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RuntimeAccessV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RuntimeAccessV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RuntimeAccessV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeAccessV1.Merge(m, src)
}
func (m *RuntimeAccessV1) XXX_Size() int {
	return m.Size()
}
func (m *RuntimeAccessV1) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeAccessV1.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeAccessV1 proto.InternalMessageInfo

func (m *RuntimeAccessV1) GetStorageBackend() *brpb.StorageBackend {
	if m != nil {
		return m.StorageBackend
	}
	return nil
}

func (m *RuntimeAccessV1) GetCipherInfo() *brpb.CipherInfo {
	if m != nil {
		return m.CipherInfo
	}
	return nil
}

// PrepareTaskResponseV1 identifies the durable PreparedResult published by
// the requested execution. The hash is exactly 32 bytes.
type PrepareTaskResponseV1 struct {
	PrepareExecutionId uint64 `protobuf:"varint,1,opt,name=prepare_execution_id,json=prepareExecutionId,proto3" json:"prepare_execution_id,omitempty"`
	PreparedResultHash []byte `protobuf:"bytes,2,opt,name=prepared_result_hash,json=preparedResultHash,proto3" json:"prepared_result_hash,omitempty"`
}

func (m *PrepareTaskResponseV1) Reset()         { *m = PrepareTaskResponseV1{} }
func (m *PrepareTaskResponseV1) String() string { return proto.CompactTextString(m) }
func (*PrepareTaskResponseV1) ProtoMessage()    {}
func (*PrepareTaskResponseV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5c0dabd4bdbfec, []int{2}
}
func (m *PrepareTaskResponseV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PrepareTaskResponseV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PrepareTaskResponseV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PrepareTaskResponseV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareTaskResponseV1.Merge(m, src)
}
func (m *PrepareTaskResponseV1) XXX_Size() int {
	return m.Size()
}
func (m *PrepareTaskResponseV1) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareTaskResponseV1.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareTaskResponseV1 proto.InternalMessageInfo

func (m *PrepareTaskResponseV1) GetPrepareExecutionId() uint64 {
	if m != nil {
		return m.PrepareExecutionId
	}
	return 0
}

func (m *PrepareTaskResponseV1) GetPreparedResultHash() []byte {
	if m != nil {
		return m.PreparedResultHash
	}
	return nil
}

// PrepareTaskErrorV1 is intentionally safe to return across the Worker HTTP
// boundary. safe_message must not include credentials, keys, or object names.
type PrepareTaskErrorV1 struct {
	Code        PrepareTaskErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=classic_restorepb.PrepareTaskErrorCode" json:"code,omitempty"`
	SafeMessage string               `protobuf:"bytes,2,opt,name=safe_message,json=safeMessage,proto3" json:"safe_message,omitempty"`
}

func (m *PrepareTaskErrorV1) Reset()         { *m = PrepareTaskErrorV1{} }
func (m *PrepareTaskErrorV1) String() string { return proto.CompactTextString(m) }
func (*PrepareTaskErrorV1) ProtoMessage()    {}
func (*PrepareTaskErrorV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5c0dabd4bdbfec, []int{3}
}
func (m *PrepareTaskErrorV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PrepareTaskErrorV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PrepareTaskErrorV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PrepareTaskErrorV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareTaskErrorV1.Merge(m, src)
}
func (m *PrepareTaskErrorV1) XXX_Size() int {
	return m.Size()
}
func (m *PrepareTaskErrorV1) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareTaskErrorV1.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareTaskErrorV1 proto.InternalMessageInfo

func (m *PrepareTaskErrorV1) GetCode() PrepareTaskErrorCode {
	if m != nil {
		return m.Code
	}
	return PrepareTaskErrorCode_PREPARE_TASK_ERROR_CODE_UNSPECIFIED
}

func (m *PrepareTaskErrorV1) GetSafeMessage() string {
	if m != nil {
		return m.SafeMessage
	}
	return ""
}

// ClassicRestoreTaskSpecV1 is the immutable intent of one Region-scoped
// Classic Restore task. Before serializing or checkpointing this message,
// producers must remove all credentials from source_backend_binding and put
// them in RuntimeAccessV1 instead. Consumers must reject a binding containing
// credentials.
type ClassicRestoreTaskSpecV1 struct {
	RestoreId       []byte              `protobuf:"bytes,1,opt,name=restore_id,json=restoreId,proto3" json:"restore_id,omitempty"`
	TaskId          []byte              `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TargetClusterId uint64              `protobuf:"varint,3,opt,name=target_cluster_id,json=targetClusterId,proto3" json:"target_cluster_id,omitempty"`
	RegionId        uint64              `protobuf:"varint,4,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	RegionEpoch     *metapb.RegionEpoch `protobuf:"bytes,5,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"`
	// The protobuf default value V1 is valid when this field is omitted.
	ApiVersion           kvrpcpb.APIVersion   `protobuf:"varint,6,opt,name=api_version,json=apiVersion,proto3,enum=kvrpcpb.APIVersion" json:"api_version,omitempty"`
	SourceBackendBinding *brpb.StorageBackend `protobuf:"bytes,7,opt,name=source_backend_binding,json=sourceBackendBinding,proto3" json:"source_backend_binding,omitempty"`
	// A task must contain at least one source descriptor.
	SourceSsts []*SourceSstV1 `protobuf:"bytes,8,rep,name=source_ssts,json=sourceSsts,proto3" json:"source_ssts,omitempty"`
}

func (m *ClassicRestoreTaskSpecV1) Reset()         { *m = ClassicRestoreTaskSpecV1{} }
func (m *ClassicRestoreTaskSpecV1) String() string { return proto.CompactTextString(m) }
func (*ClassicRestoreTaskSpecV1) ProtoMessage()    {}
func (*ClassicRestoreTaskSpecV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5c0dabd4bdbfec, []int{4}
}
func (m *ClassicRestoreTaskSpecV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClassicRestoreTaskSpecV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClassicRestoreTaskSpecV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClassicRestoreTaskSpecV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassicRestoreTaskSpecV1.Merge(m, src)
}
func (m *ClassicRestoreTaskSpecV1) XXX_Size() int {
	return m.Size()
}
func (m *ClassicRestoreTaskSpecV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassicRestoreTaskSpecV1.DiscardUnknown(m)
}

var xxx_messageInfo_ClassicRestoreTaskSpecV1 proto.InternalMessageInfo

func (m *ClassicRestoreTaskSpecV1) GetRestoreId() []byte {
	if m != nil {
		return m.RestoreId
	}
	return nil
}

func (m *ClassicRestoreTaskSpecV1) GetTaskId() []byte {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *ClassicRestoreTaskSpecV1) GetTargetClusterId() uint64 {
	if m != nil {
		return m.TargetClusterId
	}
	return 0
}

func (m *ClassicRestoreTaskSpecV1) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *ClassicRestoreTaskSpecV1) GetRegionEpoch() *metapb.RegionEpoch {
	if m != nil {
		return m.RegionEpoch
	}
	return nil
}

func (m *ClassicRestoreTaskSpecV1) GetApiVersion() kvrpcpb.APIVersion {
	if m != nil {
		return m.ApiVersion
	}
	return kvrpcpb.APIVersion_V1
}

func (m *ClassicRestoreTaskSpecV1) GetSourceBackendBinding() *brpb.StorageBackend {
	if m != nil {
		return m.SourceBackendBinding
	}
	return nil
}

func (m *ClassicRestoreTaskSpecV1) GetSourceSsts() []*SourceSstV1 {
	if m != nil {
		return m.SourceSsts
	}
	return nil
}

// SourceSstV1 contains the subset of the existing ImportSST Download request
// that the Worker needs to download, crop, and rewrite one source SST.
type SourceSstV1 struct {
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Length uint64 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	CfName string `protobuf:"bytes,3,opt,name=cf_name,json=cfName,proto3" json:"cf_name,omitempty"`
	// Post-rewrite crop range. V1 treats both bounds as inclusive, matching the
	// existing Classic transactional snapshot download path.
	Range       *import_sstpb.Range       `protobuf:"bytes,4,opt,name=range,proto3" json:"range,omitempty"`
	CipherIv    []byte                    `protobuf:"bytes,5,opt,name=cipher_iv,json=cipherIv,proto3" json:"cipher_iv,omitempty"`
	RewriteRule *import_sstpb.RewriteRule `protobuf:"bytes,6,opt,name=rewrite_rule,json=rewriteRule,proto3" json:"rewrite_rule,omitempty"`
}

func (m *SourceSstV1) Reset()         { *m = SourceSstV1{} }
func (m *SourceSstV1) String() string { return proto.CompactTextString(m) }
func (*SourceSstV1) ProtoMessage()    {}
func (*SourceSstV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5c0dabd4bdbfec, []int{5}
}
func (m *SourceSstV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SourceSstV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SourceSstV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SourceSstV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceSstV1.Merge(m, src)
}
func (m *SourceSstV1) XXX_Size() int {
	return m.Size()
}
func (m *SourceSstV1) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceSstV1.DiscardUnknown(m)
}

var xxx_messageInfo_SourceSstV1 proto.InternalMessageInfo

func (m *SourceSstV1) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SourceSstV1) GetLength() uint64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *SourceSstV1) GetCfName() string {
	if m != nil {
		return m.CfName
	}
	return ""
}

func (m *SourceSstV1) GetRange() *import_sstpb.Range {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *SourceSstV1) GetCipherIv() []byte {
	if m != nil {
		return m.CipherIv
	}
	return nil
}

func (m *SourceSstV1) GetRewriteRule() *import_sstpb.RewriteRule {
	if m != nil {
		return m.RewriteRule
	}
	return nil
}

// PreparedResultV1 is the canonical durable manifest for one completed
// physical Prepare execution. Existing field numbers and types are frozen.
type PreparedResultV1 struct {
	ProtocolVersion    uint32           `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RestoreId          []byte           `protobuf:"bytes,2,opt,name=restore_id,json=restoreId,proto3" json:"restore_id,omitempty"`
	TaskId             []byte           `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PrepareExecutionId uint64           `protobuf:"varint,4,opt,name=prepare_execution_id,json=prepareExecutionId,proto3" json:"prepare_execution_id,omitempty"`
	TaskSpecHash       []byte           `protobuf:"bytes,5,opt,name=task_spec_hash,json=taskSpecHash,proto3" json:"task_spec_hash,omitempty"`
	Outputs            []*PreparedSstV1 `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (m *PreparedResultV1) Reset()         { *m = PreparedResultV1{} }
func (m *PreparedResultV1) String() string { return proto.CompactTextString(m) }
func (*PreparedResultV1) ProtoMessage()    {}
func (*PreparedResultV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5c0dabd4bdbfec, []int{6}
}
func (m *PreparedResultV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PreparedResultV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PreparedResultV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PreparedResultV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreparedResultV1.Merge(m, src)
}
func (m *PreparedResultV1) XXX_Size() int {
	return m.Size()
}
func (m *PreparedResultV1) XXX_DiscardUnknown() {
	xxx_messageInfo_PreparedResultV1.DiscardUnknown(m)
}

var xxx_messageInfo_PreparedResultV1 proto.InternalMessageInfo

func (m *PreparedResultV1) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *PreparedResultV1) GetRestoreId() []byte {
	if m != nil {
		return m.RestoreId
	}
	return nil
}

func (m *PreparedResultV1) GetTaskId() []byte {
	if m != nil {
		return m.TaskId
	}
	return nil
}

func (m *PreparedResultV1) GetPrepareExecutionId() uint64 {
	if m != nil {
		return m.PrepareExecutionId
	}
	return 0
}

func (m *PreparedResultV1) GetTaskSpecHash() []byte {
	if m != nil {
		return m.TaskSpecHash
	}
	return nil
}

func (m *PreparedResultV1) GetOutputs() []*PreparedSstV1 {
	if m != nil {
		return m.Outputs
	}
	return nil
}

// PreparedSstV1 references one ordered final CSE SST object.
type PreparedSstV1 struct {
	FileId         uint64 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Size_          uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	PhysicalSha256 []byte `protobuf:"bytes,3,opt,name=physical_sha256,json=physicalSha256,proto3" json:"physical_sha256,omitempty"`
}

func (m *PreparedSstV1) Reset()         { *m = PreparedSstV1{} }
func (m *PreparedSstV1) String() string { return proto.CompactTextString(m) }
func (*PreparedSstV1) ProtoMessage()    {}
func (*PreparedSstV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d5c0dabd4bdbfec, []int{7}
}
func (m *PreparedSstV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PreparedSstV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PreparedSstV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PreparedSstV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreparedSstV1.Merge(m, src)
}
func (m *PreparedSstV1) XXX_Size() int {
	return m.Size()
}
func (m *PreparedSstV1) XXX_DiscardUnknown() {
	xxx_messageInfo_PreparedSstV1.DiscardUnknown(m)
}

var xxx_messageInfo_PreparedSstV1 proto.InternalMessageInfo

func (m *PreparedSstV1) GetFileId() uint64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *PreparedSstV1) GetSize_() uint64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *PreparedSstV1) GetPhysicalSha256() []byte {
	if m != nil {
		return m.PhysicalSha256
	}
	return nil
}

func init() {
	proto.RegisterEnum("classic_restorepb.PrepareTaskErrorCode", PrepareTaskErrorCode_name, PrepareTaskErrorCode_value)
	proto.RegisterType((*PrepareTaskRequestV1)(nil), "classic_restorepb.PrepareTaskRequestV1")
	proto.RegisterType((*RuntimeAccessV1)(nil), "classic_restorepb.RuntimeAccessV1")
	proto.RegisterType((*PrepareTaskResponseV1)(nil), "classic_restorepb.PrepareTaskResponseV1")
	proto.RegisterType((*PrepareTaskErrorV1)(nil), "classic_restorepb.PrepareTaskErrorV1")
	proto.RegisterType((*ClassicRestoreTaskSpecV1)(nil), "classic_restorepb.ClassicRestoreTaskSpecV1")
	proto.RegisterType((*SourceSstV1)(nil), "classic_restorepb.SourceSstV1")
	proto.RegisterType((*PreparedResultV1)(nil), "classic_restorepb.PreparedResultV1")
	proto.RegisterType((*PreparedSstV1)(nil), "classic_restorepb.PreparedSstV1")
}

func init() { proto.RegisterFile("classic_restorepb.proto", fileDescriptor_6d5c0dabd4bdbfec) }

var fileDescriptor_6d5c0dabd4bdbfec = []byte{
	// 1096 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcf, 0x73, 0xdb, 0xc4,
	0x17, 0x8f, 0x62, 0xc7, 0xb1, 0xd7, 0x4e, 0xac, 0x6e, 0xf3, 0x4d, 0xfd, 0x2d, 0xe0, 0x71, 0x43,
	0x21, 0x69, 0x61, 0x5c, 0xe2, 0x40, 0x0f, 0xc0, 0x4c, 0x47, 0x91, 0x95, 0x56, 0xd4, 0xb1, 0x3d,
	0xeb, 0x1f, 0x03, 0xa7, 0x1d, 0x45, 0x5a, 0xdb, 0x1a, 0xdb, 0x92, 0xd8, 0x95, 0xcc, 0x8f, 0xe1,
	0xc6, 0x1f, 0x00, 0xdc, 0x38, 0x72, 0xe4, 0xc8, 0x91, 0x3f, 0x81, 0x63, 0x8f, 0x3d, 0x76, 0x92,
	0x0b, 0x7f, 0x06, 0xb3, 0xbb, 0x92, 0x12, 0xa7, 0x75, 0x98, 0xe1, 0xa4, 0xf7, 0xde, 0xe7, 0xf3,
	0xde, 0xee, 0xfb, 0xb5, 0x02, 0x77, 0xec, 0x99, 0xc5, 0x98, 0x6b, 0x63, 0x4a, 0x58, 0xe8, 0x53,
	0x12, 0x9c, 0xd5, 0x03, 0xea, 0x87, 0x3e, 0xbc, 0xf5, 0x1a, 0x70, 0x17, 0x9c, 0xd1, 0x04, 0xbe,
	0xbb, 0x33, 0xf6, 0xc7, 0xbe, 0x10, 0x1f, 0x71, 0x29, 0xb6, 0x42, 0x77, 0x1e, 0xf8, 0x34, 0xc4,
	0x8c, 0x85, 0x29, 0x73, 0x6b, 0xba, 0xa0, 0x81, 0x9d, 0xaa, 0xa5, 0x39, 0x09, 0xad, 0x54, 0x2b,
	0xd3, 0x88, 0x85, 0x42, 0x94, 0x86, 0xbd, 0x3f, 0x15, 0xb0, 0xd3, 0xa5, 0x24, 0xb0, 0x28, 0xe9,
	0x5b, 0x6c, 0x8a, 0xc8, 0xd7, 0x11, 0x61, 0xe1, 0xf0, 0x10, 0x7e, 0x04, 0x76, 0x02, 0x69, 0xc7,
	0xe4, 0x5b, 0x62, 0x47, 0xa1, 0xeb, 0x7b, 0xd8, 0x75, 0x2a, 0x4a, 0x4d, 0x39, 0xc8, 0x22, 0x18,
	0x63, 0x46, 0x02, 0x99, 0x0e, 0x7c, 0x0b, 0x14, 0x42, 0x8b, 0x4d, 0x31, 0x0b, 0x88, 0x5d, 0x59,
	0xaf, 0x29, 0x07, 0x25, 0x94, 0xe7, 0x86, 0x5e, 0x40, 0x6c, 0x68, 0x82, 0x6d, 0x1a, 0x79, 0xa1,
	0x3b, 0x27, 0xd8, 0xb2, 0x6d, 0xc2, 0x58, 0x25, 0x53, 0x53, 0x0e, 0x8a, 0x8d, 0xbd, 0xfa, 0xeb,
	0x05, 0x41, 0x92, 0xa8, 0x09, 0xde, 0xf0, 0x10, 0x6d, 0xd1, 0xab, 0x86, 0x2f, 0x72, 0xf9, 0xbf,
	0x37, 0xd5, 0x3f, 0x0a, 0x7b, 0x3f, 0x29, 0xa0, 0x7c, 0x8d, 0x0a, 0x9f, 0x80, 0x32, 0x8f, 0x62,
	0x8d, 0x09, 0x3e, 0xb3, 0xec, 0x29, 0xf1, 0xe4, 0x85, 0x8b, 0x8d, 0xdd, 0x3a, 0xd7, 0xa3, 0xa0,
	0xde, 0x93, 0xf0, 0xb1, 0x44, 0xd1, 0x36, 0x5b, 0xd2, 0xe1, 0x11, 0x28, 0xda, 0x6e, 0x30, 0x21,
	0x14, 0xbb, 0xde, 0xc8, 0x17, 0x69, 0x14, 0x1b, 0x30, 0x71, 0xd6, 0x05, 0x64, 0x7a, 0x23, 0x1f,
	0x01, 0x3b, 0x95, 0xd3, 0x1b, 0xfd, 0xa8, 0x80, 0xff, 0x2d, 0x15, 0x93, 0x05, 0xbe, 0xc7, 0xc8,
	0x7f, 0xaa, 0xe6, 0xa5, 0x87, 0xc3, 0x4b, 0x13, 0xcd, 0x42, 0x3c, 0xb1, 0xd8, 0x24, 0x2e, 0x6c,
	0xe2, 0xe1, 0x20, 0x01, 0x3d, 0xb3, 0xd8, 0x24, 0xbd, 0xc5, 0x0f, 0x00, 0x5e, 0xb9, 0x84, 0x41,
	0xa9, 0x4f, 0x87, 0x87, 0xf0, 0x33, 0x90, 0xb5, 0x7d, 0x87, 0x88, 0x13, 0xb7, 0x1b, 0xfb, 0x6f,
	0x28, 0xfb, 0x75, 0x27, 0xdd, 0x77, 0x08, 0x12, 0x4e, 0xf0, 0x1e, 0x28, 0x31, 0x6b, 0x44, 0xf0,
	0x9c, 0x30, 0x66, 0x8d, 0x89, 0xb8, 0x44, 0x01, 0x15, 0xb9, 0xed, 0x54, 0x9a, 0xd2, 0xd3, 0x7f,
	0xcb, 0x80, 0x8a, 0x2e, 0x63, 0x23, 0x19, 0xba, 0x1f, 0xcf, 0xc0, 0xf0, 0x10, 0xbe, 0x03, 0x40,
	0x7c, 0x5e, 0x92, 0x7c, 0x09, 0x15, 0x62, 0x8b, 0xe9, 0xc0, 0x3b, 0x60, 0x53, 0x4c, 0x90, 0xeb,
	0xc4, 0x69, 0xe6, 0xb8, 0x6a, 0x3a, 0xf0, 0x21, 0xb8, 0x15, 0x5a, 0x74, 0x4c, 0x42, 0x6c, 0xcf,
	0x22, 0x16, 0xf2, 0xee, 0x38, 0x62, 0x80, 0xb2, 0xa8, 0x2c, 0x01, 0x5d, 0xda, 0xe5, 0x18, 0x52,
	0x32, 0x8e, 0xeb, 0x9b, 0x15, 0x9c, 0xbc, 0x34, 0x98, 0x0e, 0x7c, 0x0c, 0x4a, 0x31, 0x48, 0x02,
	0xdf, 0x9e, 0x54, 0x36, 0x44, 0x7f, 0x6f, 0xd7, 0xe3, 0x25, 0x41, 0x02, 0x33, 0x38, 0x84, 0x8a,
	0xf4, 0x52, 0x81, 0x1f, 0x83, 0xa2, 0x15, 0xb8, 0x78, 0x41, 0x28, 0x73, 0x7d, 0xaf, 0x92, 0x13,
	0x45, 0xbc, 0x5d, 0x4f, 0x56, 0x4d, 0xeb, 0x9a, 0x43, 0x09, 0x21, 0x60, 0x05, 0x6e, 0x2c, 0xc3,
	0x16, 0xd8, 0x65, 0x7e, 0x44, 0xed, 0x74, 0x18, 0xf1, 0x99, 0xeb, 0x39, 0xae, 0x37, 0xae, 0x6c,
	0xde, 0x38, 0x94, 0x3b, 0xd2, 0x2b, 0x56, 0x8f, 0xa5, 0x0f, 0x7c, 0x02, 0x8a, 0x71, 0x34, 0xc6,
	0x42, 0x56, 0xc9, 0xd7, 0x32, 0x07, 0xc5, 0x46, 0xf5, 0x0d, 0x8d, 0xec, 0x09, 0x56, 0x8f, 0xaf,
	0x31, 0x02, 0x2c, 0x51, 0x2e, 0x17, 0xe7, 0x95, 0x02, 0x8a, 0x57, 0x38, 0x10, 0x82, 0xac, 0x67,
	0xcd, 0xe5, 0x68, 0x14, 0x90, 0x90, 0xe1, 0x2e, 0xc8, 0xcd, 0x88, 0x37, 0x0e, 0xe5, 0xc0, 0x65,
	0x51, 0xac, 0xf1, 0x16, 0xd9, 0x23, 0x2c, 0xe8, 0x19, 0x41, 0xcf, 0xd9, 0xa3, 0x36, 0x77, 0x78,
	0x00, 0x36, 0xa8, 0xe5, 0x8d, 0x89, 0x28, 0x39, 0x2f, 0xe9, 0xd2, 0xd3, 0x84, 0x38, 0x84, 0x24,
	0x83, 0x77, 0x28, 0xd9, 0xb1, 0x85, 0xe8, 0x40, 0x09, 0xe5, 0xe3, 0x6d, 0x5a, 0xc0, 0xcf, 0x79,
	0x87, 0xbe, 0xa1, 0x6e, 0x48, 0x30, 0x8d, 0x66, 0x44, 0x94, 0xba, 0xd8, 0xf8, 0xff, 0xb5, 0x70,
	0x92, 0x81, 0xa2, 0x19, 0xe1, 0x7d, 0x4a, 0x95, 0x34, 0xc5, 0x5f, 0xd6, 0x81, 0xda, 0x5d, 0x5a,
	0x91, 0xe1, 0x21, 0x7c, 0x00, 0x54, 0xf1, 0xe8, 0xd9, 0xfe, 0x2c, 0xed, 0x24, 0xcf, 0x79, 0x0b,
	0x95, 0x13, 0x7b, 0xd2, 0xb9, 0xe5, 0x41, 0x5d, 0xbf, 0x61, 0x50, 0x33, 0x4b, 0x83, 0xba, 0x6a,
	0xcf, 0xb3, 0x2b, 0xf7, 0xfc, 0x3e, 0xd8, 0x4e, 0x5f, 0x4d, 0xb9, 0xe1, 0xb2, 0x22, 0xa5, 0xe4,
	0xe9, 0xe4, 0xbb, 0x0d, 0x3f, 0x05, 0x9b, 0x7e, 0x14, 0x06, 0x51, 0xc8, 0x2a, 0x39, 0xd1, 0xf7,
	0xda, 0xea, 0x05, 0x76, 0x64, 0xe7, 0x13, 0x87, 0xb4, 0x26, 0x73, 0xb0, 0xb5, 0xc4, 0xe0, 0x59,
	0x8c, 0xdc, 0x19, 0xb9, 0x7c, 0x87, 0x72, 0x5c, 0x35, 0x1d, 0x3e, 0x10, 0xcc, 0xfd, 0x9e, 0xc4,
	0xad, 0x17, 0x32, 0xdc, 0x07, 0xe5, 0x60, 0xf2, 0x1d, 0x73, 0x6d, 0x6b, 0x86, 0xd9, 0xc4, 0x6a,
	0x7c, 0xf2, 0x38, 0x4e, 0x7d, 0x3b, 0x31, 0xf7, 0x84, 0x35, 0x39, 0xee, 0xe1, 0x45, 0x66, 0xe9,
	0xcf, 0x92, 0x3e, 0x29, 0x70, 0x1f, 0xbc, 0xdb, 0x45, 0x46, 0x57, 0x43, 0x06, 0xee, 0x6b, 0xbd,
	0xe7, 0xd8, 0x40, 0xa8, 0x83, 0xb0, 0xde, 0x69, 0x1a, 0x78, 0xd0, 0xee, 0x75, 0x0d, 0xdd, 0x3c,
	0x31, 0x8d, 0xa6, 0xba, 0x06, 0x3f, 0x04, 0x07, 0xab, 0x88, 0x66, 0x7b, 0xa8, 0xb5, 0xcc, 0x26,
	0xd6, 0xd0, 0xd3, 0xc1, 0xa9, 0xd1, 0xee, 0xab, 0xca, 0xbf, 0x84, 0x1d, 0x74, 0xbb, 0x1d, 0xd4,
	0x37, 0x9a, 0xea, 0x3a, 0xac, 0x81, 0xb7, 0x57, 0x11, 0x8f, 0x07, 0xbd, 0xaf, 0xd4, 0xcc, 0x4d,
	0x07, 0x1b, 0x5f, 0x1a, 0xfa, 0xa0, 0x6f, 0x76, 0xda, 0xf8, 0x44, 0x33, 0x5b, 0x46, 0x53, 0xcd,
	0xc2, 0xf7, 0xc0, 0xbd, 0x55, 0x6c, 0x5d, 0x6b, 0xeb, 0x46, 0x8b, 0xd3, 0x36, 0xe0, 0x7d, 0x50,
	0x5b, 0x49, 0xeb, 0xb4, 0x4f, 0x5a, 0xa6, 0xde, 0x57, 0x73, 0xf0, 0x7d, 0xb0, 0xb7, 0x9a, 0x85,
	0xd0, 0xa0, 0xcb, 0xcf, 0x56, 0x37, 0x6f, 0x8a, 0x66, 0xb6, 0xfb, 0x06, 0x6a, 0x6b, 0x2d, 0x35,
	0x0f, 0x3f, 0x00, 0xfb, 0xab, 0x58, 0x7d, 0x0d, 0x3d, 0x35, 0xfa, 0xf8, 0xd4, 0xec, 0x9d, 0x6a,
	0x7d, 0xfd, 0x99, 0x5a, 0x80, 0x47, 0xe0, 0xd1, 0x2a, 0x72, 0xaf, 0x33, 0x40, 0xba, 0x81, 0x8f,
	0x35, 0xfd, 0xb9, 0xd1, 0x6e, 0x5e, 0x3a, 0x81, 0xe3, 0xc6, 0xcb, 0xdf, 0xf3, 0xca, 0x5f, 0xe7,
	0x55, 0xe5, 0xc5, 0x79, 0x55, 0x79, 0x75, 0x5e, 0x55, 0x7e, 0xbe, 0xa8, 0xae, 0xfd, 0x7a, 0x51,
	0x5d, 0x7b, 0x71, 0x51, 0x5d, 0x7b, 0x79, 0x51, 0x5d, 0x03, 0xaa, 0x4f, 0xc7, 0xf5, 0xd0, 0x9d,
	0x2e, 0xea, 0xd3, 0x85, 0x58, 0xb3, 0xb3, 0x9c, 0xf8, 0x1c, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff,
	0xe1, 0x45, 0xe4, 0x17, 0x0c, 0x09, 0x00, 0x00,
}

func (m *PrepareTaskRequestV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PrepareTaskRequestV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PrepareTaskRequestV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RuntimeAccess != nil {
		{
			size, err := m.RuntimeAccess.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintClassicRestorepb(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TaskSpec) > 0 {
		i -= len(m.TaskSpec)
		copy(dAtA[i:], m.TaskSpec)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.TaskSpec)))
		i--
		dAtA[i] = 0x12
	}
	if m.PrepareExecutionId != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.PrepareExecutionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RuntimeAccessV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RuntimeAccessV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RuntimeAccessV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CipherInfo != nil {
		{
			size, err := m.CipherInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintClassicRestorepb(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.StorageBackend != nil {
		{
			size, err := m.StorageBackend.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintClassicRestorepb(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PrepareTaskResponseV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PrepareTaskResponseV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PrepareTaskResponseV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PreparedResultHash) > 0 {
		i -= len(m.PreparedResultHash)
		copy(dAtA[i:], m.PreparedResultHash)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.PreparedResultHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.PrepareExecutionId != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.PrepareExecutionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PrepareTaskErrorV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PrepareTaskErrorV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PrepareTaskErrorV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SafeMessage) > 0 {
		i -= len(m.SafeMessage)
		copy(dAtA[i:], m.SafeMessage)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.SafeMessage)))
		i--
		dAtA[i] = 0x12
	}
	if m.Code != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ClassicRestoreTaskSpecV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClassicRestoreTaskSpecV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClassicRestoreTaskSpecV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SourceSsts) > 0 {
		for iNdEx := len(m.SourceSsts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SourceSsts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintClassicRestorepb(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.SourceBackendBinding != nil {
		{
			size, err := m.SourceBackendBinding.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintClassicRestorepb(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.ApiVersion != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.ApiVersion))
		i--
		dAtA[i] = 0x30
	}
	if m.RegionEpoch != nil {
		{
			size, err := m.RegionEpoch.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintClassicRestorepb(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.RegionId != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.RegionId))
		i--
		dAtA[i] = 0x20
	}
	if m.TargetClusterId != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.TargetClusterId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RestoreId) > 0 {
		i -= len(m.RestoreId)
		copy(dAtA[i:], m.RestoreId)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.RestoreId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SourceSstV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SourceSstV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SourceSstV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RewriteRule != nil {
		{
			size, err := m.RewriteRule.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintClassicRestorepb(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.CipherIv) > 0 {
		i -= len(m.CipherIv)
		copy(dAtA[i:], m.CipherIv)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.CipherIv)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Range != nil {
		{
			size, err := m.Range.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintClassicRestorepb(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.CfName) > 0 {
		i -= len(m.CfName)
		copy(dAtA[i:], m.CfName)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.CfName)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Length != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.Length))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PreparedResultV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PreparedResultV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PreparedResultV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Outputs) > 0 {
		for iNdEx := len(m.Outputs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Outputs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintClassicRestorepb(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.TaskSpecHash) > 0 {
		i -= len(m.TaskSpecHash)
		copy(dAtA[i:], m.TaskSpecHash)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.TaskSpecHash)))
		i--
		dAtA[i] = 0x2a
	}
	if m.PrepareExecutionId != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.PrepareExecutionId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RestoreId) > 0 {
		i -= len(m.RestoreId)
		copy(dAtA[i:], m.RestoreId)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.RestoreId)))
		i--
		dAtA[i] = 0x12
	}
	if m.ProtocolVersion != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.ProtocolVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PreparedSstV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PreparedSstV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PreparedSstV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PhysicalSha256) > 0 {
		i -= len(m.PhysicalSha256)
		copy(dAtA[i:], m.PhysicalSha256)
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(len(m.PhysicalSha256)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Size_ != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x10
	}
	if m.FileId != 0 {
		i = encodeVarintClassicRestorepb(dAtA, i, uint64(m.FileId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintClassicRestorepb(dAtA []byte, offset int, v uint64) int {
	offset -= sovClassicRestorepb(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PrepareTaskRequestV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PrepareExecutionId != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.PrepareExecutionId))
	}
	l = len(m.TaskSpec)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	if m.RuntimeAccess != nil {
		l = m.RuntimeAccess.Size()
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	return n
}

func (m *RuntimeAccessV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StorageBackend != nil {
		l = m.StorageBackend.Size()
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	if m.CipherInfo != nil {
		l = m.CipherInfo.Size()
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	return n
}

func (m *PrepareTaskResponseV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PrepareExecutionId != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.PrepareExecutionId))
	}
	l = len(m.PreparedResultHash)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	return n
}

func (m *PrepareTaskErrorV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.Code))
	}
	l = len(m.SafeMessage)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	return n
}

func (m *ClassicRestoreTaskSpecV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RestoreId)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	if m.TargetClusterId != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.TargetClusterId))
	}
	if m.RegionId != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.RegionId))
	}
	if m.RegionEpoch != nil {
		l = m.RegionEpoch.Size()
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	if m.ApiVersion != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.ApiVersion))
	}
	if m.SourceBackendBinding != nil {
		l = m.SourceBackendBinding.Size()
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	if len(m.SourceSsts) > 0 {
		for _, e := range m.SourceSsts {
			l = e.Size()
			n += 1 + l + sovClassicRestorepb(uint64(l))
		}
	}
	return n
}

func (m *SourceSstV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	if m.Length != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.Length))
	}
	l = len(m.CfName)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	if m.Range != nil {
		l = m.Range.Size()
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	l = len(m.CipherIv)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	if m.RewriteRule != nil {
		l = m.RewriteRule.Size()
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	return n
}

func (m *PreparedResultV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProtocolVersion != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.ProtocolVersion))
	}
	l = len(m.RestoreId)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	if m.PrepareExecutionId != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.PrepareExecutionId))
	}
	l = len(m.TaskSpecHash)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	if len(m.Outputs) > 0 {
		for _, e := range m.Outputs {
			l = e.Size()
			n += 1 + l + sovClassicRestorepb(uint64(l))
		}
	}
	return n
}

func (m *PreparedSstV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FileId != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.FileId))
	}
	if m.Size_ != 0 {
		n += 1 + sovClassicRestorepb(uint64(m.Size_))
	}
	l = len(m.PhysicalSha256)
	if l > 0 {
		n += 1 + l + sovClassicRestorepb(uint64(l))
	}
	return n
}

func sovClassicRestorepb(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClassicRestorepb(x uint64) (n int) {
	return sovClassicRestorepb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PrepareTaskRequestV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassicRestorepb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PrepareTaskRequestV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PrepareTaskRequestV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepareExecutionId", wireType)
			}
			m.PrepareExecutionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrepareExecutionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskSpec", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskSpec = append(m.TaskSpec[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskSpec == nil {
				m.TaskSpec = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuntimeAccess", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RuntimeAccess == nil {
				m.RuntimeAccess = &RuntimeAccessV1{}
			}
			if err := m.RuntimeAccess.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassicRestorepb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RuntimeAccessV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassicRestorepb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RuntimeAccessV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RuntimeAccessV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageBackend", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StorageBackend == nil {
				m.StorageBackend = &brpb.StorageBackend{}
			}
			if err := m.StorageBackend.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CipherInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CipherInfo == nil {
				m.CipherInfo = &brpb.CipherInfo{}
			}
			if err := m.CipherInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassicRestorepb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PrepareTaskResponseV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassicRestorepb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PrepareTaskResponseV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PrepareTaskResponseV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepareExecutionId", wireType)
			}
			m.PrepareExecutionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrepareExecutionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreparedResultHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreparedResultHash = append(m.PreparedResultHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PreparedResultHash == nil {
				m.PreparedResultHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassicRestorepb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PrepareTaskErrorV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassicRestorepb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PrepareTaskErrorV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PrepareTaskErrorV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= PrepareTaskErrorCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SafeMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SafeMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassicRestorepb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClassicRestoreTaskSpecV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassicRestorepb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClassicRestoreTaskSpecV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClassicRestoreTaskSpecV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RestoreId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RestoreId = append(m.RestoreId[:0], dAtA[iNdEx:postIndex]...)
			if m.RestoreId == nil {
				m.RestoreId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = append(m.TaskId[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskId == nil {
				m.TaskId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetClusterId", wireType)
			}
			m.TargetClusterId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetClusterId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			m.RegionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionEpoch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegionEpoch == nil {
				m.RegionEpoch = &metapb.RegionEpoch{}
			}
			if err := m.RegionEpoch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiVersion", wireType)
			}
			m.ApiVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApiVersion |= kvrpcpb.APIVersion(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceBackendBinding", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SourceBackendBinding == nil {
				m.SourceBackendBinding = &brpb.StorageBackend{}
			}
			if err := m.SourceBackendBinding.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceSsts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceSsts = append(m.SourceSsts, &SourceSstV1{})
			if err := m.SourceSsts[len(m.SourceSsts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassicRestorepb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SourceSstV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassicRestorepb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SourceSstV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SourceSstV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Length", wireType)
			}
			m.Length = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Length |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CfName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CfName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Range", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Range == nil {
				m.Range = &import_sstpb.Range{}
			}
			if err := m.Range.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CipherIv", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CipherIv = append(m.CipherIv[:0], dAtA[iNdEx:postIndex]...)
			if m.CipherIv == nil {
				m.CipherIv = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewriteRule", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RewriteRule == nil {
				m.RewriteRule = &import_sstpb.RewriteRule{}
			}
			if err := m.RewriteRule.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassicRestorepb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PreparedResultV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassicRestorepb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PreparedResultV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PreparedResultV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolVersion", wireType)
			}
			m.ProtocolVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtocolVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RestoreId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RestoreId = append(m.RestoreId[:0], dAtA[iNdEx:postIndex]...)
			if m.RestoreId == nil {
				m.RestoreId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = append(m.TaskId[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskId == nil {
				m.TaskId = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepareExecutionId", wireType)
			}
			m.PrepareExecutionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrepareExecutionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskSpecHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskSpecHash = append(m.TaskSpecHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TaskSpecHash == nil {
				m.TaskSpecHash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Outputs = append(m.Outputs, &PreparedSstV1{})
			if err := m.Outputs[len(m.Outputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassicRestorepb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PreparedSstV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClassicRestorepb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PreparedSstV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PreparedSstV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileId", wireType)
			}
			m.FileId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhysicalSha256", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PhysicalSha256 = append(m.PhysicalSha256[:0], dAtA[iNdEx:postIndex]...)
			if m.PhysicalSha256 == nil {
				m.PhysicalSha256 = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClassicRestorepb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClassicRestorepb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClassicRestorepb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClassicRestorepb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClassicRestorepb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClassicRestorepb
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClassicRestorepb
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClassicRestorepb
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClassicRestorepb        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClassicRestorepb          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClassicRestorepb = fmt.Errorf("proto: unexpected end of group")
)
